# Generated by Django 6.0.6 on 2026-06-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='clerk_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='clerk_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
