# Generated by Django 6.0.6 on 2026-06-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_landlord_clerk_user_id_tenant_clerk_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
    ]
