# Generated by Django 6.0.6 on 2026-06-19 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_landlord_user_remove_tenant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='house_videos/'),
        ),
        migrations.CreateModel(
            name='HousePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_photos/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='core.house')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
