# Generated by Django 6.0.6 on 2026-06-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_tenant',
            field=models.BooleanField(default=False),
        ),
    ]
