# Generated by Django 6.0.6 on 2026-06-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactmessage_house_number_contactmessage_is_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricitybill',
            options={'ordering': ['-month']},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['house_id']},
        ),
        migrations.AlterModelOptions(
            name='landlord',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-month']},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='waterbill',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='month',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_id',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='is_occupied',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='clerk_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='clerk_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
