# Generated by Django 6.0.6 on 2026-06-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_electricitybill_options_alter_house_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricitybill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={},
        ),
        migrations.AlterModelOptions(
            name='landlord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='waterbill',
            options={},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='clerk_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='clerk_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='date',
            field=models.DateField(),
        ),
    ]
